In [1]:
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing import sequence

In [2]:
max_features = 2000
max_len =500

In [3]:
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=max_features)

In [4]:
x_train = sequence.pad_sequences(x_train , maxlen = max_len)

In [13]:
x_train

array([[  0,   0,   0, ...,  19, 178,  32],
       [  0,   0,   0, ...,  16, 145,  95],
       [  0,   0,   0, ...,   7, 129, 113],
       ...,
       [  0,   0,   0, ...,   4,   2,   2],
       [  0,   0,   0, ...,  12,   9,  23],
       [  0,   0,   0, ..., 204, 131,   9]], dtype=int32)

In [5]:
x_test = sequence.pad_sequences(x_test , maxlen = max_len)

In [6]:
model = keras.models.Sequential()
model.add(layers.Embedding(max_features, 128 , input_length = max_len, name='embed'))
model.add(layers.MaxPooling1D(5))
model.add(layers.Conv1D(32, 7, activation='relu'))
model.add(layers.GlobalMaxPooling1D())
model.add(layers.Dense(1))
model.summary()
model.compile(optimizer='rmsprop',
loss='binary_crossentropy',
metrics=['acc'])

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embed (Embedding)            (None, 500, 128)          256000    
_________________________________________________________________
max_pooling1d (MaxPooling1D) (None, 100, 128)          0         
_________________________________________________________________
conv1d (Conv1D)              (None, 94, 32)            28704     
_________________________________________________________________
global_max_pooling1d (Global (None, 32)                0         
_________________________________________________________________
dense (Dense)                (None, 1)                 33        
Total params: 284,737
Trainable params: 284,737
Non-trainable params: 0
_________________________________________________________________


In [8]:
callbacks = [keras.callbacks.TensorBoard(log_dir = 'my_log_dir', histogram_freq= 1, embeddings_freq=1)]

In [9]:
history = model.fit(x_train, y_train,
epochs=20,
batch_size=128,
validation_split=0.2,
callbacks=callbacks
                   )

Epoch 1/20
157/157 [==============================] - 9s 55ms/step - loss: 0.6306 - acc: 0.6258 - val_loss: 0.5502 - val_acc: 0.7484
Epoch 2/20
157/157 [==============================] - 9s 55ms/step - loss: 0.4595 - acc: 0.8245 - val_loss: 0.4204 - val_acc: 0.8472
Epoch 3/20
157/157 [==============================] - 9s 55ms/step - loss: 0.3574 - acc: 0.8788 - val_loss: 0.4601 - val_acc: 0.8424
Epoch 4/20
157/157 [==============================] - 8s 53ms/step - loss: 0.3127 - acc: 0.8983 - val_loss: 0.7813 - val_acc: 0.8140
Epoch 5/20
157/157 [==============================] - 8s 53ms/step - loss: 0.2717 - acc: 0.9201 - val_loss: 0.5263 - val_acc: 0.8730
Epoch 6/20
157/157 [==============================] - 9s 56ms/step - loss: 0.2269 - acc: 0.9379 - val_loss: 0.5806 - val_acc: 0.8662
Epoch 7/20
157/157 [==============================] - 9s 55ms/step - loss: 0.1839 - acc: 0.9560 - val_loss: 0.5484 - val_acc: 0.8792
Epoch 8/20
157/157 [==============================] - 9s 55ms/step - 

In [10]:
import os
PATH = os.getenv('PATH')
%env PATH=/Users/pankaj/anaconda/envs/ML2/bin:$PATH
%load_ext tensorboard
%tensorboard --logdir my_log_dir

env: PATH=/Users/pankaj/anaconda/envs/ML2/bin:/Users/pankaj/anaconda/condabin:/Users/pankaj/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin


ERROR: Failed to launch TensorBoard (exited with -6).
Contents of stderr:
[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/descriptor_database.cc:393] Invalid file descriptor data passed to EncodedDescriptorDatabase::Add().
[libprotobuf FATAL external/com_google_protobuf/src/google/protobuf/descriptor.cc:1367] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
libc++abi.dylib: terminating with uncaught exception of type google::protobuf::FatalException: CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):

In [11]:
import numpy as np
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

{0: 'toxic',
 1: 'severe_toxic',
 2: 'obscene',
 3: 'threat',
 4: 'insult',
 5: 'identity_hate'}