In [4]:
import torch
import pandas as pd

In [15]:
def describe(tf):
    print("type : ", tf.type)
    print("Shape:" , tf.shape)
    print(tf)

In [7]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
x = torch.ones(3,4)

In [16]:
describe(x)

type :  <built-in method type of Tensor object at 0x1274c4a00>
Shape: torch.Size([3, 4])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [18]:
print(torch.cuda.is_available())

False


In [20]:
a= torch.rand(2,3)

In [21]:
a

tensor([[0.8818, 0.0336, 0.9121],
        [0.6039, 0.3171, 0.5495]])

In [22]:
a.unsqueeze(0)

tensor([[[0.8818, 0.0336, 0.9121],
         [0.6039, 0.3171, 0.5495]]])

In [23]:
describe(a)

type :  <built-in method type of Tensor object at 0x1274d0cd0>
Shape: torch.Size([2, 3])
tensor([[0.8818, 0.0336, 0.9121],
        [0.6039, 0.3171, 0.5495]])


In [25]:
b = a.unsqueeze(0)

In [26]:
describe(b)

type :  <built-in method type of Tensor object at 0x1274d6730>
Shape: torch.Size([1, 2, 3])
tensor([[[0.8818, 0.0336, 0.9121],
         [0.6039, 0.3171, 0.5495]]])


In [27]:
b.squeeze()

tensor([[0.8818, 0.0336, 0.9121],
        [0.6039, 0.3171, 0.5495]])

In [31]:
describe(a.squeeze().squeeze())

type :  <built-in method type of Tensor object at 0x1274df870>
Shape: torch.Size([2, 3])
tensor([[0.8818, 0.0336, 0.9121],
        [0.6039, 0.3171, 0.5495]])


In [33]:
import spacy

In [38]:
from fastai import *
from fastai.text import *

In [39]:
??URLs