In [1]:
from sklearn import *
from tensorflow import keras as keras
# import matplotlib.pyplot as plt
import tensorflow as tf
from sklearn.datasets import load_digits
from tensorflow.keras.utils import to_categorical
import pandas as pd
import os
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Flatten, Dense
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
from tensorboard.plugins import projector

root_dir = r'/Users/shantanu/Library/Mobile Documents/com~apple~CloudDocs/Capstone/Wikipedia Data'


result_path = annot_file_path = os.path.join(root_dir , 'comments_with_grouped_annoptations.tsv')

merged_comments = pd.read_table(result_path)


In [2]:
merged_comments['recipient_attack'] = merged_comments['recipient_attack'].apply(lambda x : 1 if x> 1 else 0 )
X_train = merged_comments['comment']
y = merged_comments['recipient_attack']
one_hot_train_labels = to_categorical(y)

In [3]:
merged_comments['new_attack'] = merged_comments['attack'].apply(lambda x : 1 if x> 1 else 0 )

### TODO change model with proper word settings 

In [4]:
# Prepare training input  
training_samples = 90000
validation_samples = 10000
max_words = 15000
tokenizer = Tokenizer(num_words=max_words)
tokenizer.fit_on_texts(X_train)
sequences = tokenizer.texts_to_sequences(X_train)
word_index = tokenizer.word_index
print('Found %s unique tokens.' % len(word_index))


Found 187899 unique tokens.


In [5]:
maxlen = 150

In [6]:
data = pad_sequences(sequences, maxlen=maxlen)
print('Shape of data tensor:', data.shape)
indices = np.arange(data.shape[0])
np.random.shuffle(indices)
data = data[indices]
x_train = data[:training_samples]
x_val = data[training_samples: (training_samples + validation_samples)]
x_test = data[(training_samples + validation_samples) : ]

Shape of data tensor: (115864, 150)


In [7]:
# Prepare labels 
labels = np.asarray(one_hot_train_labels)
print('Shape of label tensor:', labels.shape)
labels = labels[indices]
y_train = labels[:training_samples]
y_val = labels[training_samples: training_samples + validation_samples]
y_test = labels[(training_samples + validation_samples) : ]

Shape of label tensor: (115864, 2)


In [8]:
from tensorflow.keras.layers import LSTM
embedding_dim = 16
model = Sequential()
#embedding = Embedding(max_words, embedding_dim , weights =w)
embedding = Embedding(max_words, embedding_dim)

#embedding.trainable = False
model.add(embedding)
model.add(LSTM(128,return_sequences = True))
model.add(LSTM(64))
model.add(Flatten())
model.add(Dense(32, activation='relu'))
model.add(Dense(2, activation='sigmoid'))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, None, 16)          240000    
_________________________________________________________________
lstm (LSTM)                  (None, None, 128)         74240     
_________________________________________________________________
lstm_1 (LSTM)                (None, 64)                49408     
_________________________________________________________________
flatten (Flatten)            (None, 64)                0         
_________________________________________________________________
dense (Dense)                (None, 32)                2080      
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 66        
Total params: 365,794
Trainable params: 365,794
Non-trainable params: 0
__________________________________________________

In [9]:
model.compile(optimizer='rmsprop',
loss='binary_crossentropy',
metrics=['acc'])
history = model.fit(x_train, y_train,
epochs= 2,
batch_size=128,
validation_data=(x_val, y_val))

Train on 90000 samples, validate on 10000 samples
Epoch 1/2
90000/90000 [==============================] - 283s 3ms/sample - loss: 0.3672 - acc: 0.8483 - val_loss: 0.3410 - val_acc: 0.8682
Epoch 2/2
90000/90000 [==============================] - 285s 3ms/sample - loss: 0.3075 - acc: 0.8753 - val_loss: 0.3589 - val_acc: 0.8698


In [10]:
model.save('basic_lstm_with_auto_encoder.h5')

In [13]:
word_index_1 = {k: v+3 for k, v in word_index.items()}
word_index_1['<padding>'] = 0
word_index_1['<start>'] = 1
word_index_1['<unknown>'] = 2

counter = 3



In [14]:
def preprocess_text(text_eval):
    sequences = tokenizer.texts_to_sequences([text_eval])
    data = pad_sequences(sequences, maxlen=maxlen)
    return data

In [15]:
d = preprocess_text("white card pankaj wq adqwd dqwwq ") 

In [16]:
len(d[0])

150

In [17]:
x_train_1 = merged_comments[:training_samples]

In [18]:
x_train_1.head()

Unnamed: 0  rev_id                                            comment  \
0           0   37675  `-NEWLINE_TOKENThis is not ``creative``.  Thos...   
1           1   44816  `NEWLINE_TOKENNEWLINE_TOKEN:: the term ``stand...   
2           2   49851  NEWLINE_TOKENNEWLINE_TOKENTrue or false, the s...   
3           3   89320   Next, maybe you could work on being less cond...   
4           4   93890               This page will need disambiguation.    

   year  logged_in       ns  sample  split  worker_id  quoting_attack  \
0  2002      False  article  random  train       9721             0.0   
1  2002      False  article  random  train      20234             0.0   
2  2002      False  article  random  train      26474             0.0   
3  2002       True  article  random    dev      26738             0.0   
4  2002       True  article  random  train       8010             0.0   

   recipient_attack  third_party_attack  other_attack  attack  new_attack  
0                 0                 0.0           0.0     0.0           0  
1                 0                 0.0           0.0     0.0           0  
2                 0                 0.0           0.0     0.0           0  
3                 1                 0.0           2.0     4.0           1  
4                 0                 0.0           0.0     0.0           0

In [19]:
x_train_1 = merged_comments[:training_samples]
x_val_1 = merged_comments[training_samples: (training_samples + validation_samples)]
x_test_1 = merged_comments[(training_samples + validation_samples) : ]

In [20]:
x_train_1.head()

Unnamed: 0  rev_id                                            comment  \
0           0   37675  `-NEWLINE_TOKENThis is not ``creative``.  Thos...   
1           1   44816  `NEWLINE_TOKENNEWLINE_TOKEN:: the term ``stand...   
2           2   49851  NEWLINE_TOKENNEWLINE_TOKENTrue or false, the s...   
3           3   89320   Next, maybe you could work on being less cond...   
4           4   93890               This page will need disambiguation.    

   year  logged_in       ns  sample  split  worker_id  quoting_attack  \
0  2002      False  article  random  train       9721             0.0   
1  2002      False  article  random  train      20234             0.0   
2  2002      False  article  random  train      26474             0.0   
3  2002       True  article  random    dev      26738             0.0   
4  2002       True  article  random  train       8010             0.0   

   recipient_attack  third_party_attack  other_attack  attack  new_attack  
0                 0                 0.0           0.0     0.0           0  
1                 0                 0.0           0.0     0.0           0  
2                 0                 0.0           0.0     0.0           0  
3                 1                 0.0           2.0     4.0           1  
4                 0                 0.0           0.0     0.0           0

In [21]:
import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords 
import tensorflow_hub as hub


In [22]:
 pred_vlaues = model.predict(preprocess_text(str("dark night sas")))

In [23]:
pred_vlaues

array([[0.8229963 , 0.16675597]], dtype=float32)

In [28]:
embed = hub.load("/Users/shantanu/GitHub/capstone/elmo_3")
# embed = hub.load(module_url)

In [31]:
NAE_vals_array = np.empty((3,1024), float)
# NAE_vals_array = []
PAE_vals_array = np.empty((3,1024), float)

for index, row in x_train_1.iterrows():
    print(" running count {}".format(index))
    text = row.comment.translate(str.maketrans('','',string.punctuation))
    tokens = word_tokenize(text)
    tokens_without_sw = [word for word in tokens if not word in stopwords.words()]
   
    ### First Get the overall Classification
    pred_vlaues = model.predict(preprocess_text(str(tokens_without_sw)))
    classification = pred_vlaues.argmax()
    
    if classification == 0 and row.recipient_attack == 0:
        mode = 'PAE' # Positive AutoEncoder
    elif classification == 0 and row.recipient_attack == 1:
        mode = 'NAE'
    elif classification == 1 and row.recipient_attack == 0:
        mode = 'PAE'
    elif classification == 1 and row.recipient_attack == 1:
        mode = 'NAE'
    ### Get the Elmo vector
    text=tf.convert_to_tensor([str(tokens_without_sw)])
    out = embed.signatures['default'](text)['elmo']
    pred_vals_array = np.empty((0,2), float)
    
    for i in range(len(tokens_without_sw)-2):
        text_eval = tokens_without_sw[i:i+3]
        a = preprocess_text(str(text_eval))
        pred_vlaues = model.predict(a)
        print(a)
        print(pred_vlaues)
        pred_vals_array = np.vstack((pred_vals_array,pred_vlaues))
    if mode == "NAE":
        # Only Negative Vals, and find the index of the highest contributing phrase
        phrase_start_index = pred_vals_array[:,1].argmax()
        ### Get the ELMO Encoding of the entire vector:
        elmo_vecs = np.array(out[0][phrase_start_index:phrase_start_index+3])
        NAE_vals_array = np.vstack((NAE_vals_array, elmo_vecs))
    elif mode == "PAE":
        # Only Positive Vals, and find the index of the highest contributing phrase
        phrase_start_index = pred_vals_array[:,0].argmax()
        PAE_vals_array = np.vstack((PAE_vals_array,out[0][phrase_start_index:phrase_start_index+3]))
    if index == 10:
        break

 running count 0
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0]]
[[0.7772767  0.21281666]]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0]]
[[0.7772767  0.21281666]]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0

KeyboardInterrupt: 

In [54]:
row

0         0
1         0
2         0
3         0
4         0
       ... 
145       6
146       1
147     891
148    2264
149    1935
Name: 0, Length: 150, dtype: int32

In [76]:
NAE_vals_array = NAE_vals_array.reshape(int(NAE_vals_array.shape[0]/3),3,1024)


In [77]:
# lstm autoencoder to recreate a timeseries
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import RepeatVector
from tensorflow.keras.layers import TimeDistributed
from tensorflow.keras.callbacks import EarlyStopping

In [78]:
timesteps = 3
n_features = 1024
es = EarlyStopping(monitor='val_loss', mode='min', verbose=1)

# define model
model_TAE = Sequential()
model_TAE .add(LSTM(1024, activation='relu', input_shape=(timesteps,n_features), return_sequences=True))
model_TAE .add(LSTM(720, activation='relu', input_shape=(timesteps,n_features), return_sequences=True))
model_TAE .add(LSTM(128, activation='relu', input_shape=(timesteps,n_features), return_sequences=True))
model_TAE .add(LSTM(64, activation='relu', return_sequences=False))
model_TAE .add(RepeatVector(timesteps))
model_TAE .add(LSTM(64, activation='relu', return_sequences=True))
model_TAE .add(LSTM(128, activation='relu', return_sequences=True))
model_TAE .add(LSTM(720, activation='relu', return_sequences=True))
model_TAE .add(LSTM(1027, activation='relu', return_sequences=True))
model_TAE .add(TimeDistributed(Dense(n_features)))
model_TAE .compile(optimizer='adam', loss='mse')
model_TAE.summary()
# model_TAE .fit(aa, aa, epochs=3, batch_size=5)

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, None, 16)          240000    
_________________________________________________________________
lstm_1 (LSTM)                (None, 32)                6272      
_________________________________________________________________
flatten_1 (Flatten)          (None, 32)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 32)                1056      
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 66        
Total params: 247,394
Trainable params: 247,394
Non-trainable params: 0
_________________________________________________________________


In [80]:
model_TAE.summary()
model_TAE.fit(NAE_vals_array, NAE_vals_array, epochs=3, batch_size=5)

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_2 (LSTM)                (None, 3, 1024)           8392704   
_________________________________________________________________
lstm_3 (LSTM)                (None, 3, 720)            5025600   
_________________________________________________________________
lstm_4 (LSTM)                (None, 3, 128)            434688    
_________________________________________________________________
lstm_5 (LSTM)                (None, 64)                49408     
_________________________________________________________________
repeat_vector (RepeatVector) (None, 3, 64)             0         
_________________________________________________________________
lstm_6 (LSTM)                (None, 3, 64)             33024     
_________________________________________________________________
lstm_7 (LSTM)                (None, 3, 128)           